version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: loyalty-saas-db
    environment:
      POSTGRES_DB: loyalty_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: loyalty-saas-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loyalty.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

